[SRE-141] Enable hlint of sub-directories
input-output-hk/iohk-nix pull request #441
Opened 2020-10-09 07:50 UTC by craigem

Hydra is currently unable to `hlint` projects in sub-directories because it consumes `selectProjectPackages` which only provides a package name which `hlint` then assumes is in the root.

This is an interim workaround.

2020-10-09 10:15 UTC, jbgi commented
I see. Can you remove the `projects` arg altogether, since it's not used anymore? Users can use the `src` argument to select projects if needed.

2020-10-09 10:16 UTC, jbgi requested changes
I see. Can you remove the projects arg altogether, since it's not used anymore? Users can use the src argument to select projects if needed.

2020-10-13 02:57 UTC, sevanspowell approved these changes

2020-10-13 05:35 UTC, craigem commented
bors r+

2020-10-13 05:38 UTC, merged