add metadataUrl
input-output-hk/iohk-nix pull request #467
Opened 2021-02-16 13:34 UTC by disassembler

2021-02-16 13:40 UTC, jbgi requested changes

2021-02-16 13:40 UTC, jbgi commented on cardano-lib/default.nix
> +      metadataUrl = "https://metadata.cardano-testnet.iohkdev.io";
```suggestion
      metadataUrl = "https://metadata.staging.cardano.org";
```

2021-02-16 13:40 UTC, jbgi commented on cardano-lib/default.nix
> +      metadataUrl = "https://metadata.cardano-testnet.iohkdev.io";
```suggestion
      metadataUrl = "https://metadata.shelley-qa.dev.cardano.org";
```

2021-02-16 13:42 UTC, jbgi approved these changes

2021-02-17 08:15 UTC, nikolaglumac approved these changes

2021-02-17 08:15 UTC, nikolaglumac commented
@jbgi @disassembler can we please have this one merged? 🙏

2021-02-17 09:10 UTC, nikolaglumac commented
We have already integrated this into Daedalus: https://github.com/input-output-hk/daedalus/pull/2292/commits/79517144f1d35e0c0f6f85d16866b1cdef7cd299

2021-02-26 20:45 UTC, johnalotoski commented
bors r+

2021-02-26 20:47 UTC, merged