Add Conway support
input-output-hk/iohk-nix pull request #527
Opened 2023-03-03 04:02 UTC by erikd

2023-03-04 02:24 UTC, disassembler requested changes
This is missing conway genesis JSON file added for each environment. It also references mainnet directory for all environments.

2023-03-04 02:24 UTC, disassembler commented on cardano-lib/mainnet-config.nix
> +  ConwayGenesisFile = ./mainnet + "/alonzo-genesis.json";
Should be conway

2023-03-04 02:24 UTC, disassembler commented on cardano-lib/marlowe-pioneers-config.nix
> +  ConwayGenesisFile = ./mainnet + "/alonzo-genesis.json";
Should be conway

2023-03-04 02:24 UTC, disassembler commented on cardano-lib/p2p-config.nix
> +  ConwayGenesisFile = ./mainnet + "/alonzo-genesis.json";
Should be conway

2023-03-04 02:24 UTC, disassembler commented on cardano-lib/preprod-config.nix
> +  ConwayGenesisFile = ./mainnet + "/alonzo-genesis.json";
Should be conway

2023-03-04 02:24 UTC, disassembler commented on cardano-lib/preview-config.nix
> +  ConwayGenesisFile = ./mainnet + "/alonzo-genesis.json";
Should be conway

2023-03-04 02:24 UTC, disassembler commented on cardano-lib/shelley_qa-config.nix
> +  ConwayGenesisFile = ./mainnet + "/alonzo-genesis.json";
Should be conway

2023-03-04 02:24 UTC, disassembler commented on cardano-lib/sre.nix
> +  ConwayGenesisFile = ./mainnet + "/alonzo-genesis.json";
Should be conway

2023-03-04 02:24 UTC, disassembler commented on cardano-lib/staging-config.nix
> +  ConwayGenesisFile = ./mainnet + "/alonzo-genesis.json";
Should be conway

2023-03-04 02:24 UTC, disassembler commented on cardano-lib/testnet-config.nix
> +  ConwayGenesisFile = ./mainnet + "/alonzo-genesis.json";
Should be conway

2023-03-04 02:24 UTC, disassembler commented on cardano-lib/vasil-dev-config.nix
> +  ConwayGenesisFile = ./mainnet + "/alonzo-genesis.json";
Should be conway

2023-03-04 06:21 UTC, erikd commented
I have fixed what you pointed out as obviously wrong. I do not know how to fix the rest (or test that its right).

2023-03-09 01:36 UTC, angerman approved these changes

2023-03-09 01:36 UTC, angerman commented
Added "(dummy)" to the Conway genesis link, just to make sure the casual reader is not confused.

2023-03-09 01:36 UTC, angerman commented
bors try

2023-03-09 01:56 UTC, merged